name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.11.1
    - name: Analysing src with pylint
      run: |
        python lint.py --path ./src --threshold 9
    - name: Analysing tests with pylint
      run: |
        python lint.py --path ./tests --threshold 9
    - name: Analysing examples with pylint
      run: |
        python lint.py --path ./examples --threshold 8
